services:
  db1:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "toto"
    ports:
      - '5432:5432'
    networks:
      - postgres

  db2:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "tata"
    ports:
      - '5433:5432'
    networks:
      - postgres

  db3:
    image: redis:7-alpine
    command: redis-server --requirepass tutu
    ports:
      - '6380:6379'

networks:
  postgres:
    driver: bridge